innovationacademy-kr/42dashboard

packages/client/src/dashboard/presentation/components/Sticker/StickerBody.tsx
StickerBody Component 추가
#90
- Sticker 내 차트 또는 테이블이 보여질 영역 필요
- 차트 종류나 테이블을 props로 받아 해당 컨텐츠를 보여주는 StickerBody Component 추가
=> feat(Sticker): feat: add StickerBody Component

packages/client/src/dashboard/presentation/components/Charts/PieChart.tsx
- PieChart function에 default를 붙여 Sticker에서 import할 때 build error가 난것을 고쳤습니다.
main으로 merge를 했을 때 git action build error가 났습니다.
🐛 버그 픽스인 경우 :
- 버그의 발생 원인? 코드를 수정하면서 Sticker 파트에서 쓰는 PieChart function에 default로 export를 하지 않았습니다.
- 어떻게 해결했는가? PieChart export에서 default를 붙여주었습니다.
=> fix(client/charts): fix build error

packages/client/src/dashboard/presentation/components/Board/Section.tsx, packages/client/src/dashboard/presentation/components/Sticker/Sticker.tsx
Header, StickerBody를 포함한 Sticker Component 추가
#88
- 차트 및 테이블을 보여주기 위한 Sticker 필요
- Header, StickerBody를 포함한 Sticker Component 생성
- Section에서 Sticker 추가 시, 임의의 데이터(PieChart)가 포함된 Sticker를 생성하도록 수정
=> feat(Sticker): feat: Sticker Component 추가

packages/server/src/app.module.ts, packages/server/src/schema.gql, packages/server/src/user_information/user_information.service.ts, packages/server/src/user_status/entity/user_status.entity.ts
- 진행상황의 자료형을 변경하고, datasource에 종속성주입을 하였습니다.
- 1600명 목업데이터로 파싱확인했습니다.
fix #125
- 1600명 데이터를 추출하기 위해 모든 컬럼에 목업데이터를 구성하여 파싱테스트를 하고자 했습니다.
- 엔티티의 타입변경
- Datasource의 종속성주입
=> fix(server): fixed: progress entity type changed

packages/server/src/updater/name_types/updater.name.ts, packages/server/src/user_information/argstype/userAccessCardInformation.ts, packages/server/src/user_information/entity/user_access_card_information.entity.ts, packages/server/src/user_information/entity/user_information.entity.ts
테이블 컬럼의 긴 이름과 불명확한 해석을 수정하였습니다
style #138
API 명세를 작성하기 위해 테이블 컬럼을 수정하였습니다. 
- 테이블 컬럼 수정
- ex) lapiscine_access_card_number_of_physical -> lapiscine_physical_number
=> style(userAccessCardInformationArgs): style: change column name

packages/server/src/user_information/user_information.service.spec.ts, packages/server/src/user_information/user_information.service.ts
In 연산자를 지원하여 필터링시 or연산이 일부 가능하게 구현을 해놓았습니다
feat #143
var In [1, 2, 3] 은 var이 1또는 2또는 3일때 true인 연산인데, 이 연산을 지원하게 하여
기수 In ["1기", "2기", "3기"] 등의 필터링이 가능하게 하였습니다.
=> feat(server): or 연산자 일부 지원

packages/server/src/user_information/filter.ts, packages/server/src/user_information/user_information.resolver.ts, packages/server/src/user_information/user_information.service.ts
오타 몇개를 수정하였습니다. 연산자 3개를 추가하였습니다 (between, like, ilike)연산자를 추가하였습니다
fix #157
🐛 버그 픽스인 경우 :
- 버그를 재현하는 방법?: 오타에 의해서 발생한 버그입니다.
- 버그의 발생 원인?: 오타입니다.
- 어떻게 해결했는가?: 오타를 수정했습니다 죄송합니다.
✨ 그 외의 경우 :
- 적용된 변경 사항 요약
getPeopleByFiter 쿼리를 getPeopleByFilter로 오타수정. lastest -> latest 오타 수정
연산자 3개 수정 -> api 명세서에 설명을 적어 놓았습니다.
=> fix(server): 오타 수정(lastest, fiter) 및 연산자 추가

packages/server/src/api/api.controller.ts, packages/server/src/api/api.module.ts, packages/server/src/api/api.service.ts, packages/server/src/api/dto/create-api.dto.ts, packages/server/src/api/entity/api.entity.ts, packages/server/src/schema.gql, packages/server/src/updater/name_types/updater.name.ts, packages/server/src/updater/updater.module.ts, packages/server/src/updater/updater.service.ts, packages/server/src/user_information/user_information.module.ts, packages/server/src/user_information/user_information.service.spec.ts, packages/server/src/user_information/user_information.service.ts, packages/server/src/user_status/entity/user_status.entity.ts
updater에서 스프레드를 받아오는 로직 이후에 api를 받아오는 로직 추가
"feat #55", "docs #107"
update 모듈로 42api를 요청하여 값을 받아와 DB에 저장하고자 함
- api 모듈 추가
- 구글 스프레드 시트에서 받아오는 데이터중 api 가 필요한 데이터들을 채워서 db에 저장
- api데이터로만 구성된 DB테이블에 데이터 저장
- 아직 circle값과 coalition_score값 , phone 값을 받아오지 못하고 있습니다.
- phone의 경우 보안및 권한이 필요한 부분이고, circle과 coalition_score의 경우 api end-point를 찾지 못하였습니다.
- 추후에 받아올 수 있도록 하겠습니다.
=> feat(server): api 파싱하여 db에 저장

packages/server/src/auth/auth.module.ts, packages/server/src/auth/auth.service.ts, packages/server/src/auth/entity/bocal.entity.ts, packages/server/src/auth/jwt.strategy.ts, packages/server/src/schema.gql, packages/server/src/user_information/argstype/cudDto.argstype.ts, packages/server/src/user_information/argstype/filter.argstype.ts, packages/server/src/user_information/argstype/joinedTable.ts, packages/server/src/user_information/entity/user_access_card_information.entity.ts, packages/server/src/user_information/entity/user_information.entity.ts, packages/server/src/user_information/entity/user_other_information.entity.ts, packages/server/src/user_information/entity/user_personal_information.entity.ts, packages/server/src/user_information/filter.ts, packages/server/src/user_information/user_information.controller.ts, packages/server/src/user_information/user_information.module.ts, packages/server/src/user_information/user_information.resolver.ts, packages/server/src/user_information/user_information.service.ts, packages/server/src/user_job/entity/user_job.entity.ts, packages/server/src/user_payment/entity/user_computation_fund.entity.ts, packages/server/src/user_payment/entity/user_education_fund_state.entity.ts, packages/server/src/user_payment/entity/user_payment.entity.ts, packages/server/src/user_status/entity/user_status.entity.ts
관리자(admin)을 위한 graphql query 및 mutation 구현
각각의 엔터티에 deleted_date 컬럼 추가
사이트이용자(bocal)들의 정보를 저장하는 테이블 추가
filter조건에 take, skip옵션 추가
feat #176
관리자(루나님과 같은 admin)를 위한 graphql query, mutation을 추가하였습니다.
graphql api를 통해서 DB의 데이터를 update, delete, recover(delete된 것을 recover)하는 것이 가능하게 되었습니다.
recover이 가능하도록 deleted_date 컬럼을 추가, softRemove 메서드를 사용하였습니다.
api 사용 명세는 조만간 노션에 업데이트 하겠습니다.
사이트 이용자(bocal)들의 데이터를 저장하는 테이블인 bocal table을 추가하였습니다.
(폴라베어님 요청) 하나의 api 요청시 데이터를 몇개씩 들고올수 있는지 정할수있는 옵션을 넣어두었습니다.(skip, take)
(이것도 노션에 업데이트 해놓겠습니다.)
=> feat(server): 관리자를 위한 graphql api 추가

packages/server/src/api/api.service.ts, packages/server/src/schema.gql, packages/server/src/updater/name_types/updater.name.ts, packages/server/src/updater/updater.controller.ts, packages/server/src/updater/updater.module.ts, packages/server/src/updater/updater.resolver.ts, packages/server/src/updater/updater.service.ts, packages/server/src/user_information/entity/user_access_card_information.entity.ts, packages/server/src/user_information/entity/user_other_information.entity.ts, packages/server/src/user_information/entity/user_personal_information.entity.ts, packages/server/src/user_job/entity/user_job.entity.ts, packages/server/src/user_payment/entity/user_computation_fund.entity.ts, packages/server/src/user_payment/entity/user_education_fund_state.entity.ts, packages/server/src/user_status/entity/user_status.entity.ts
- 하위시트를 파싱하기 위해 코드를 작성하였습니다.
- 커밋 충돌을 해결하기위해 수정하던 중, 멘토링을 통한 코드리뷰 후 복잡한 코드를 조금 더 간결하게 수정하였습니다.
첫번째 커밋 수정
- 하위시트를 파싱하기 위해 함수를 추가하였습니다.
- 기존 엔터티에 외래키 제약조건을 일부 해제하였습니다.
- 메인시트에 없던 컬럼들을 추가적으로 넣어 구성하였습니다.
- 기존 메인시트파싱이 유연하기 이뤄지지 않아, 테이블 구분 방식을 수정하였습니다.
충돌 이후 두번째 커밋
- 중복되는 함수 삭제 
- 하위시트 여러컬럼생성하는 부분 수정(같은 일자는 같은 로우)
- api로 데이터받아올 때, 스탭데이터만 받아와지는 오류 수정
- 충돌로 인해 생긴 오류 수정
- 변수 이름 변경
- 반복문의 중첩의 경우, 스프레드시트의 정보를 받아오는 특성때문에 고치지 못하였습니다.
=> fixed: refactoring and api error

packages/server/src/user_information/entity/user_access_card_information.entity.ts, packages/server/src/user_information/entity/user_information.entity.ts, packages/server/src/user_information/entity/user_personal_information.entity.ts
personal & accesscard 엔티티 관계 수정
fix #208
entity 수정
user_personal_infomation
user_access_card_information
의 관계를 one to one 에서 many to one으로 변경
=> fix(server/updater): fixed: fix entity relation

packages/client/src/dashboard/application/services/useBoard.tsx, packages/client/src/dashboard/application/services/useMode.tsx, packages/client/src/dashboard/application/services/useSectionDatas.tsx, packages/client/src/dashboard/domain/controlMode/controlMode.repository.interface.ts, packages/client/src/dashboard/domain/controlMode/controlMode.service.ts, packages/client/src/dashboard/infrastructure/controlMode.repository.ts, packages/client/src/dashboard/presentation/components/Board/Board.tsx, packages/client/src/dashboard/presentation/components/Board/Section.tsx, packages/client/src/dashboard/presentation/components/Common/EditToolBar.tsx, packages/client/src/dashboard/presentation/components/ModeDial/ModeDial.tsx, packages/client/src/dashboard/presentation/components/Sticker/Sticker.tsx
- ControlMode 중, edit 모드의 경우에만 보드, 섹션, 스티커를 컨트롤 할 수 있는 EditToolBar가 보이도록 작업
- 기존에 모드 변경을 위해 적용된 redux를 PAID 구조에 맞춰 변경
- Board 내 Add Section, Save Preset 적용
- Section 내 Add Sticker 적용
=> feat(mode): ControlMode에 따른 EditToolBar 렌더링

packages/client/src/dashboard/presentation/components/Charts/BarChart.tsx, packages/client/src/dashboard/presentation/components/Charts/LineChart.tsx, packages/client/src/dashboard/presentation/components/Charts/PieChart.tsx, packages/client/src/dashboard/presentation/components/Common/EditToolBar.tsx, packages/client/src/dashboard/presentation/components/Sticker/StickerContentFactory.tsx
Sticker 내 Component가 높이에 대해 크기 조절이 되지 않는 문제 해결
#313
- Chart가 높이에 대해서도 크기가 조절되도록 변경
- Chart에 default options 적용
- Sticker 내 Component를 래핑하여 사이즈 조절
=> feat(sticker): feat: Sticker 내 Component 크기 제한

packages/client/src/dashboard/presentation/components/ModeDial/ModeDial.tsx
edit mode의 경우, 기존 ModeDial을 렌더하지 않고 view mode로 변환하는 버튼 렌더
#289
- edit mode 가 아닌 경우, 기존의 ModeDial 렌더
- edit mode 의 경우, view mode로 전환하는 버튼 렌더
=> feat(ModeDial): feat: edit mode시, ModeDial 변경

packages/client/src/dashboard/presentation/components/Board/Board.tsx
🐛 버그 픽스인 경우 :
- 윈도우 리사이즈로 변경된 레이아웃이 저장이 되어 다시 화면이 커졌을때 변경되지 않았던 문제
- 변경되는 breakpoints 지점들을 제거 해서 해결했습니다.
=> fix(client): save layout change when window resize event occur

packages/server/src/schema.gql, packages/server/src/spread/spread.service.ts, packages/server/src/updater/updater.resolver.ts, packages/server/src/updater/updater.service.ts, packages/server/src/user_information/argstype/updateSheet.argstype.ts, packages/server/src/user_information/utils/getDomain.utils.ts
feat #307
- pgadmin을 대신해서 수정 작업을 할 수있는 api를  따로 구성하였습니다.
- getDataToModifyFromDB을 사용하여 특정 테이블의 Data를 가져온 뒤, table의 이름으로 sheet를 생성
- sheet에 있는 데이터를 직접 수정 가능
- 불러온 sheet의 컬럼과 키에 색상 추가예정
- saveModifiedDataFromSheet을 사용하여 가져온 데이터를 DB에 다시 저장 후 sheet 삭제
- 사용자가 수정할 수 있는 범위를 추가예정
예시코드 
```query {
getDataToModifyFromDB(sheetName: "userComputationFund")
}
query {
saveModifiedDataFromSheet(sheetName: "user")
}
```
=> fix(server): feated: add API for Edit process

packages/client/package.json, packages/client/src/dashboard/application/services/useUser.tsx, packages/client/src/dashboard/domain/user/user.repository.interface.ts, packages/client/src/dashboard/domain/user/user.service.ts, packages/client/src/dashboard/infrastructure/http/axios/axios.custom.ts, packages/client/src/dashboard/infrastructure/store/zustand/dashboard.store.zustand.ts, packages/client/src/dashboard/infrastructure/user.repository.ts, packages/client/src/dashboard/presentation/components/Login/Login.tsx, packages/client/src/dashboard/presentation/pages/DashBoardPage.tsx, yarn.lock
user data 조회 및 저장
#301
- 유저의 로그인 여부에 따른 동작
- 유저가 로그인 시, API를 통해 유저의 정보 추출 및 저장
- zustand에 persist 미들웨어 적용
- 로그인하지 않은 유저가 dashboard에 접근 시, 로그인 페이지로 라우팅
- /dashboard path에서 로그인이 되어 있지 않은 경우, / path로 navigate 처리는 잘 되지만,
/ path에서 로그인이 되어 있는 경우, /dashboard path로 navigate가 되지 않는 현상이 있습니다.
zustand의 persist 미들웨어를 통해 스토어 내에 유저데이터가 저장되어 있어 로그인이 되어 있는 경우의 조건문에 들어가는 건 확인했습니다.
해당 이슈 추가 발행 예정입니다.
=> feat(User): feat: set user data

packages/client/src/dashboard/application/services/usePreset.tsx
- 사이드바에서 presetlist에서 item을 선택해야지만 보고싶은 board가 렌더링되는 불편함을 해소하기 위함.
- 프리셋이 없을 때 프리셋 추가가 용이하도록 edit 모드로 렌더링하기 위함.
- 적용된 변경 사항 요약
- presetlist에 아이템이 있다면 첫번째 아이템 선택해서 렌더링하고, 없다면 edit모드로 default preset 활성화
=> feat(client/board): presetlist에 아이템 유무에 따른 보드 렌더링 처리

packages/client/src/dashboard/application/services/usePreset.tsx, packages/client/src/dashboard/infrastructure/presetList.repository.ts, packages/client/src/dashboard/presentation/components/SideBar/PresetListItem.tsx, packages/client/src/dashboard/presentation/components/SideBar/SideBar.tsx, packages/client/src/dashboard/presentation/components/SideBar/SideBarListItem.tsx
preset마다 제목을 변경할 수 있도록 하고 싶었습니다.
- 적용된 변경 사항 요약
- preset마다 제목을 변경할 수 있도록 하였고, 새로고침 하더라도 제목이 저장될 수 있도록 하였습니다.
- preset를 추가할 때 바로 edit 모드로 변경되게 하였습니다.
제목 변경하는 방법이 살짝 복잡한데.. 더 좋은 아이디어가 있으시면 언제든지 말씀해주세요 :) !
=> preset마다 제목을 변경할 수 있는 컴포넌트 만들기

packages/server/src/schema.gql, packages/server/src/spread/msg/errorMsg.msg.ts, packages/server/src/spread/spread.service.ts, packages/server/src/updater/name_types/updater.name.ts, packages/server/src/updater/updater.service.ts, packages/server/src/user_job/entity/user_job.entity.ts
데이터 수정을 간편하게 하기 위해 구글 스프레드 상에서 작업을 할 수 있도록 환경을 구축하였습니다.
자유도가 높은 구글 스프레드 환경에서 작업할 시, 수 많은 에러가 예상 될 수 있기에 예외처리를 추가해줬습니다.
- 수정시트를 관리할때 발생할 수 있는 에러에 대해 예외처리를 추가해줬습니다
```tsx
COLUMNS = '컬럼의 이름이 변경되었거나, 수가 변동되었습니다.',
DUPLICATE = '기본키의 값이 중복되었습니다.',
INTERRUPT = '기존 데이터베이스의 값이 변동되었습니다',
CHANGED = '최신 데이터가 수정되었습니다.',
INSERT = '삽입된 데이터의 날짜와 형식을 확인해주세요',
UPDATE = '갱신된 데이터의 날짜와 형식을 확인해주세요',
SUCCESS = '수정된 데이터가 성공적으로 저장되었습니다.',
```
- **컬럼**(**청록색 데이터**)의 이름을 변경할 수 없습니다.
- 데이터베이스의 **기본키(PK) 및 외래키(fk_user_no)** (**분홍색 데이터**)의 값을 수정할 수 없습니다.
- 데이터베이스의 **최신 데이터**(**보라색 데이터**)를 변경할 수 없습니다.
- 새로운 값을 삽입할 경우 항상 **최신데이터**(**보라색 데이터**)보다 이전 시점이어야합니다.
- 기존 값을 변경할 경우 항상 **최신데이터**(**보라색 데이터**)보다 이전 시점이어야합니다.
=> feat(server/modify): feat: add modify exception

packages/client/src/dashboard/presentation/components/Modal/Modal.tsx, packages/client/src/dashboard/presentation/components/Modal/StickerStepper.tsx
- modal에서 데이터 설정을 하던 중, modal을 끄고 다시 켜면 데이터가 남아있었습니다.
- stepper에서 현재 step을 알 수 없었습니다. 
- 적용된 변경 사항 요약
- useState를 사용하여 데이터 설정 중 modal이 꺼졌었는지 확인합니다.
- 현재 step을 알 수 있게 했습니다.
feat #365 #366
=> feat(client/modal): modal 중간에 멈출 시 데이터 리셋, stepper 현재 step 표시

packages/client/src/dashboard/presentation/components/Modal/Modal.tsx
🐛 버그 픽스인 경우 :
- 모달창이 랜더가 일어나서 초기화가 일어날 경우 이중배열이 아니라 일차원 배열로 초기화가 되서 첫 데이터셋이 랜더가 안됐습니다.
=> fix(client): hotfix, initial dataset is not render

docker-compose.yml, packages/client/src/dashboard/application/services/useBoard.tsx, packages/client/src/dashboard/application/services/usePreset.tsx, packages/client/src/dashboard/domain/preset/preset.repository.interface.ts, packages/client/src/dashboard/domain/preset/preset.service.ts, packages/client/src/dashboard/infrastructure/http/axios/axios.instance.ts, packages/client/src/dashboard/infrastructure/preset.repository.ts, packages/client/src/dashboard/infrastructure/presetList.repository.ts, packages/client/src/dashboard/presentation/components/Board/Section.tsx, packages/client/src/dashboard/presentation/components/SideBar/PresetListItem.tsx, packages/server/src/auth/auth.controller.ts, packages/server/src/schema.gql, packages/server/src/user_information/user_information.controller.ts
- 로컬에 저장하던 프리셋 데이터를 DB로 옮겼습니다.
- 적용된 변경 사항 요약
- 백엔드 api를 사용하여 프리셋 저장, 수정, 삭제를 할 수 있게 하였습니다.
아직 dashboard42.com으로 프리셋 api가 되지 않기 때문에 임시로 로컬에 백엔드 서버를 올려서 완성하였습니다. 추후 도메인에 프리셋 api가 사용 가능할 때 붙이도록 하겠습니다!
usePreset에서 deletePreset 함수를 만들고 싶었는데 usePreset 내에서 무한 렌더링이되어 임시로 useBoard에 만들었습니다.
추후 수정되어야 할 사항입니다.
#368
=> feat(client): 백엔드 api를 사용하여 프리셋 저장, 수정, 삭제

packages/client/src/dashboard/presentation/components/Board/Section.tsx, packages/client/src/dashboard/presentation/components/Charts/BarChart.tsx, packages/client/src/dashboard/presentation/components/Charts/PieChart.tsx, packages/server/package.json
* 데이터셋에 이름 넣고 하는데 파이랑 바 차트는 적용이 안되더군요.
🐛 버그 픽스인 경우 :
- 파이와 바 차트에 데이터셋 이름을 적용했고
- 섹션에 브레이크 포인트도 삭제 했습니다.
=> feat(client): apply datasetnaming to pie and bar chart 

packages/server/src/spread/spread.service.ts, packages/server/src/updater/name_types/updater.name.ts, packages/server/src/updater/updater.service.ts
프론트에서 최신 값을 불러올 때 validate_date로 값을 불러오고 있습니다.
과거 데이터의 기준을 validate_date로 명확하게 지정하고자 하였습니다.
✨ 그 외의 경우 :
- 적용된 변경 사항 요약
학습데이터의 로깅 값을 저장할 때 기준이 되는 날짜를 확인하여 validate_date에 초기화
=> feat(server/updater): 학습데이터 기준 일자 변경

packages/client/src/dashboard/application/services/useBoard.tsx, packages/client/src/dashboard/presentation/components/Common/EditToolBar.tsx, packages/client/src/dashboard/presentation/components/Dialog/EntityListItem.tsx, packages/client/src/dashboard/presentation/components/Dialog/RequestButton.tsx, packages/client/src/dashboard/presentation/components/Dialog/SaveButton.tsx
🐛 버그 픽스인 경우 :
- 버그를 재현하는 방법?
- 스프레드시트를 잘못 수정 후에 저장을 누르면 에러가 발생한다.
- 이후 다시 수정사항을 되돌리고 나서 다시 요청을 보내도 같은 에러가 발생했다.
- 어떻게 해결했는가?
- gql을 쓰다보니 캐시가 적용되서 적용되는 캐쉬 정책을 바꿔주었다.
- 로딩중에 다른 스피닝다이얼을 띄워주지 않고 있다.
- 그냥 rest api요청으로 해결할 수 있다면 좋을듯.싶기도 하다.
=> fix(client): refetch when modify spread sheet

packages/client/src/App.tsx, packages/client/src/dashboard/infrastructure/http/axios/axios.custom.ts, packages/client/src/dashboard/infrastructure/http/axios/axios.instance.ts, packages/client/src/dashboard/infrastructure/preset.repository.ts, packages/client/src/dashboard/infrastructure/presetList.repository.ts
#523 
- axios를 사용한 곳을 custom axios로 변경
- User 정보를 지워야해서 hook을 사용함
- axios interceptor 내부에서 hook을 사용하지 못하기 때문에 컴포넌트로 만들어 사용 [🔗](https://velog.io/@soongle/React-hook-axios-axios-interceptor-%EB%82%B4%EB%B6%80%EC%97%90%EC%84%9C-react-hook-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0)
=> feat(client): axios로 401 error받았을 때 login 페이지로 라우팅
