innovationacademy-kr/42dashboard

packages/client/package.json
packages/client/src/App.tsx
packages/client/src/dashboard/presentation/components/Board/Board.tsx
packages/client/src/dashboard/presentation/components/Board/index.tsx
packages/client/src/dashboard/presentation/components/Board/styles.css
packages/client/src/dashboard/presentation/components/Board/styles2.css
packages/client/src/dashboard/presentation/components/Section/Section.tsx
packages/client/src/dashboard/presentation/components/Section/styles.css
packages/client/src/dashboard/presentation/components/Section/styles2.css
packages/client/src/index.tsx

✨ 적용된 변경 사항 요약
- Board와 Section의 기본 구조를 만들었습니다.
* 기존 작업에 추가된 사항으로 섹션과 스티커 모두 드래그 이동이 가능 합니다. 하지만 resize 이벤트가 발생하거나 layout 변경시에
자연스럽게 작동하지 않아 어색한 부분이 있습니다.

feat(board section): add: structure board section

---

.github/workflows/yarn-grunt.yaml

* 이번에 학습한 github action을 적용
* 
✨ 그 외의 경우 :
- 전체 레포에 대한 `lint`체크
- 앞단 디렉토리에 대한 `build`체크

add: github action: lint check & front build

---

packages/client/src/dashboard/presentation/components/ModeDial/ModeDial.tsx
packages/client/src/dashboard/presentation/pages/DashBoardPage.tsx

DashBoardPage에 ModeDial을 추가하기
- 적용된 변경 사항 요약
ModeDial Component를 추가하였습니다
ModeDial에 fullview 옵션을 생각해서 Box 컴포넌트 바로 아래에 위치하였습니다
더 좋은 의견이 있으시면 말씀해주세요! :)
#134

feat(client/dashboardpage): add modedial component

---

packages/client/src/dashboard/presentation/components/Board/Board.tsx
packages/client/src/dashboard/presentation/components/Board/Section.tsx
packages/client/src/dashboard/presentation/components/Button/InvisibleButton.tsx
packages/client/src/dashboard/presentation/components/Common/Header.tsx
packages/client/src/dashboard/presentation/components/Common/HeaderButtons.tsx
packages/client/src/dashboard/presentation/components/Sticker/Sticker.tsx
packages/client/src/dashboard/presentation/components/Sticker/StickerBody.tsx

* section과 sticker에 버튼(헤더)를 달아 주었습니다.
🐛 버그 픽스인 경우 :
- 현재 섹션과 스티커 삭제시에 key값에 들어가는 `count`를 하나씩 줄여주는데
- 나중에 섹션이나 스티커 끼리 key값이 중복될 가능성이 있어 추후 업데이트가 필요합니다. 
✨ 그 외의 경우 :
- header: remove

add: header to section and sticker

---

packages/server/src/app.module.ts
packages/server/src/schema.gql
packages/server/src/updater/updater.resolver.ts

resolver업데이트를 했습니다
feat #145
프론트에서 graphql폴링을 통해 주기적으로 업데이트가 가능하다는 내용을 전달받고, graphql방식으로 데이터를 업데이트가 가능하도록 기능을 추가하였습니다.
resolver추가
- 요청 전송 후, 데이터 확인하시고 회신 부탁드립니다.

feat(updater.resolver): updater의 graphQL요청방식 추가

---

packages/client/package.json
packages/client/src/dashboard/infrastructure/redux/actions.ts
packages/client/src/dashboard/infrastructure/redux/hooks.ts
packages/client/src/dashboard/infrastructure/redux/slices/boardModeSlice.ts
packages/client/src/dashboard/infrastructure/redux/store.ts
packages/client/src/dashboard/presentation/components/ModeDial/ModeDial.tsx
packages/client/src/index.tsx
yarn.lock

redux 설정 및 redux를 통한 mode state 관리
#79
- redux를 통한 상태 관리
- redux toolkit을 이용한 초기 설정
- mode dial에 redux를 통한 상태관리 적용
- Chrome Extension - Redux DevTools 설치 후, 개발자 도구에서 디버깅 툴 사용이 가능합니다.

feat(client): feat: setup redux

---

packages/server/src/spread/spread.service.ts
packages/server/src/user_information/entity/user_access_card_information.entity.ts
packages/server/src/user_information/entity/user_other_information.entity.ts
packages/server/src/user_information/entity/user_personal_information.entity.ts
packages/server/src/user_job/entity/user_job.entity.ts
packages/server/src/user_payment/entity/user_computation_fund.entity.ts
packages/server/src/user_payment/entity/user_education_fund_state.entity.ts
packages/server/src/user_status/entity/user_status.entity.ts

사용자 기입 오류로 인한 버그를 방지해주기 위해 제약조건을 해제해줬었는데, db에 좋지 않은 영향을 끼칠 것 같아 다시 true로 설정을 바꿨습니다.
fix #204
사용자 기입 오류 대비책 강구
외래키 제약조건 설정
✨ 그 외의 경우 :
- 적용된 변경 사항 요약

fix(server/spread): fixed: creaForeignKeyConstraints to be true

---

packages/client/src/dashboard/application/services/useFiltersModal.tsx
packages/client/src/dashboard/domain/filtersModal/filtersModal.repository.interface.ts
packages/client/src/dashboard/domain/filtersModal/filtersModal.service.ts
packages/client/src/dashboard/infrastructure/filtersModal.repository.ts
packages/client/src/dashboard/infrastructure/store/filtersModal.store.ts
packages/client/src/dashboard/infrastructure/store/zustand/dashboard.store.zustand.ts
packages/client/src/dashboard/presentation/components/Board/Board.tsx
packages/client/src/dashboard/presentation/components/Modal/Modal.tsx
packages/client/src/dashboard/presentation/components/Modal/TestComponent.tsx

add modal and apply state control library
add #80
- 필터를 생성할 옵션을 받는 모달창을 생성하고 paid구조를 적용하였음.
✨ 그 외의 경우 :
- 적용된 변경 사항 요약

feat(client/modal): add: filters modal

---

packages/client/src/dashboard/domain/boardData/boardData.repository.interface.ts
packages/client/src/dashboard/domain/boardData/boardData.service.ts
packages/client/src/dashboard/domain/boardData/boardData.type.ts
packages/client/src/dashboard/infrastructure/boardData.repository.ts
packages/client/src/dashboard/infrastructure/store/boardData.store.ts
packages/client/src/dashboard/infrastructure/store/zustand/dashboard.store.zustand.ts

- 설계대로 boardData를 만들자.
- 설계 문서 #190 에 작성된 boardData 구조대로 코드 작성
fix #218

feat(client): boardData 도메인 관련 PAID 구조로 코드 작성

---

packages/client/src/dashboard/application/services/useBoard.tsx
packages/client/src/dashboard/application/services/useSectionDatas.tsx
packages/client/src/dashboard/domain/boardData/boardData.repository.interface.ts
packages/client/src/dashboard/domain/boardData/boardData.service.ts
packages/client/src/dashboard/domain/boardData/boardData.type.ts
packages/client/src/dashboard/domain/sectionDatas/sectionData.service.ts
packages/client/src/dashboard/domain/sectionDatas/sectionData.type.ts
packages/client/src/dashboard/domain/sectionDatas/sectionDatas.repository.interface.ts
packages/client/src/dashboard/infrastructure/boardData.repository.ts
packages/client/src/dashboard/infrastructure/sectionDatas.repository.ts
packages/client/src/dashboard/infrastructure/store/boardData.store.ts
packages/client/src/dashboard/infrastructure/store/sectionDatas.store.ts
packages/client/src/dashboard/infrastructure/store/zustand/dashboard.store.zustand.ts
packages/client/src/dashboard/presentation/components/Board/Board.tsx
packages/client/src/dashboard/presentation/components/Board/Section.tsx

- 설계를 반영하여 Board, Section 컴포넌트를 수정하고자 했습니다.
- Board, Section 컴포넌트에서 사용하는 로직을 커스텀 hook 으로 작성했습니다.
- `useBoard` 훅을 작성하여 `boardData` 조작 관련 로직을 통합했습니다.
- `useSections` 훅을 작성하여 `sectionDatas` 조작 관련 로직을
통합했습니다.
- Board, Section 컴포넌트를 커스텀 훅을 사용하는 방식으로 수정했습니다.
- 커밋 단위가 너무 커서 죄송합니다. ㅜㅜ ( 납기일 임박.. )

feat(client): board -> section -> sticker PAID 구조 작업

---

packages/server/src/schema.gql
packages/server/src/updater/name_types/updater.name.ts
packages/server/src/user_information/entity/user_other_information.entity.ts
packages/server/src/user_job/entity/user_job.entity.ts
packages/server/src/user_status/entity/user_status.entity.ts

entity 변경에 따라 erd cloud를 수정하였습니다.
fix #222 
- intern 테이블의 삭제
- other information 특정 컬럼 삭제

fix: erd cloud and entity

---

packages/server/src/schema.gql
packages/server/src/updater/name_types/updater.name.ts
packages/server/src/user_information/entity/user_information.entity.ts
packages/server/src/user_information/user_information.service.ts
packages/server/src/user_job/entity/user_job.entity.ts

- 병합시, 생겼던 충돌에러를 해결하였습니다
- 엔티티 중첩사항 수정
- mapObj 의 중복된 데이터 삭제

fix(server): fixed: conflict error

---

packages/server/package.json
packages/server/src/auth/auth.controller.ts
packages/server/src/auth/auth.service.ts
packages/server/src/auth/entity/bocal.entity.ts
packages/server/src/auth/jwt.strategy.ts
packages/server/src/main.ts
packages/server/src/user_information/user_information.controller.ts
packages/server/src/user_information/user_information.service.spec.ts
packages/server/src/user_information/user_information.service.ts
packages/server/src/utils/testing-helpers/createMemDB.ts
yarn.lock

프론트에서 로그인 구현할때 필요한 api를 구현하였습니다.
auth.controller쪽에 메서드 하나 추가

feat(server): 프론트 로그인 구현시 필요한 api 구현

---

packages/client/src/dashboard/infrastructure/http/graphql/createValueQuery.ts
packages/client/src/dashboard/presentation/components/Modal/LabelFilter.tsx
packages/client/src/dashboard/presentation/components/Modal/useValueDataset.tsx
packages/client/src/index.tsx
packages/common/src/EntityColumn.ts

filter로 만든 StickerData를 만들기 위한 작업입니다.
- 적용된 변경 사항 요약
entityName, column에 따른 value를 선택할 수 있는 filter를 만들었습니다
아직 section이 여러 개일 때 modal들이 겹쳐서 뜨는 이슈와
entityName을 바꾸고 그에 맞는 column으로 바꾸기 전 query를 보내는 이슈는 고치지 못하였습니다!
곧.. 고치겠습니다..
#266

feat(component/modal): value 받아오는 api 사용하여 value filter 구현

---

.gitignore
packages/client/src/dashboard/application/services/useFiltersModal.tsx
packages/client/src/dashboard/application/services/useStickers.tsx
packages/client/src/dashboard/domain/filtersModal/filtersModal.service.ts
packages/client/src/dashboard/domain/stickerDatas/stickerDatas.repository.interface.ts
packages/client/src/dashboard/domain/stickerDatas/stickerDatas.service.ts
packages/client/src/dashboard/infrastructure/http/graphql/createQuery.ts
packages/client/src/dashboard/infrastructure/stickerDatas.repository.ts
packages/client/src/dashboard/presentation/components/Board/Section.tsx
packages/client/src/dashboard/presentation/components/Modal/DatasetAccordion.tsx
packages/client/src/dashboard/presentation/components/Modal/DatasetFilter.tsx
packages/client/src/dashboard/presentation/components/Modal/Filters.tsx
packages/client/src/dashboard/presentation/components/Modal/InputDataset.tsx
packages/client/src/dashboard/presentation/components/Modal/Modal.tsx
packages/client/src/dashboard/presentation/components/Modal/Stepper.tsx
packages/client/src/dashboard/presentation/components/Modal/TypeBox.tsx
packages/client/src/dashboard/presentation/components/Modal/forms/FilterAttribute.tsx
packages/client/src/dashboard/presentation/components/Modal/forms/LabelForm.tsx
packages/client/src/dashboard/presentation/components/Modal/forms/LatestForm.tsx
packages/client/src/dashboard/presentation/components/Modal/forms/menuItems/returnColumns.tsx
packages/client/src/dashboard/presentation/components/Modal/forms/menuItems/returnEntities.tsx
packages/client/src/dashboard/presentation/components/Modal/forms/menuItems/returnOperators.tsx
packages/client/src/dashboard/presentation/components/Modal/forms/menuItems/returnValues.tsx
packages/client/src/dashboard/presentation/components/Modal/makeStickerData.ts

✨ 그 외의 경우 :
- modal에 dataset부분도 합쳤습니다.
- modal쪽 코드를 1차적으로 리팩토링 진행했습니다.
- naming부분과 그외 큰 틀에서 좀 더 작업이 필요합니다.

Feat/#238 & refactoring

---

packages/server/src/schema.gql
packages/server/src/updater/name_types/updater.name.ts

비고 remark 로 되어있던 휴학테이블 컬럼을 uniqueness로 수정
스프레드에 특이사항이라고 되어있는 컬럼 비고로 되어있어 수정이 필요하다 느꼈습니다.
또한, 유저테이블과 휴학테이블 지원금 테이블에 특이사항 컬럼이 있는데, 데이터가 나뉘어 잘 받아지는지 확인하고자 합니다.
혹시 앞서 PR 했던 코드에서 예기치 못한 동작이 있을까싶어 바로 연이어 PR 합니다.

refactor(server): entity name 수정

---

.github/workflows/common-lint.yaml
packages/server/package.json
packages/server/src/app.module.ts
packages/server/src/schema.gql
packages/server/src/spread/spread.resolver.ts
packages/server/src/spread/spread.service.ts
packages/server/src/updater/name_types/updater.name.ts
packages/server/src/updater/updater.resolver.ts
packages/server/src/updater/updater.service.ts
packages/server/src/user_status/user_status.resolver.ts
packages/server/tsconfig.json

데이터 보안을 위해 데이터 추출방식을 변경하였습니다.
feat https://github.com/innovationacademy-kr/42dashboard/issues/268
작업 동기 (Motivation)
기존 json형태로 들어오던 데이터가 [[][]] 이중배열형식으로 변경됨에 따라, 파싱 방식의 일부가 수정되었습니다.
구글 스프레드 접근을 위한 키가 새로 추가 되었습니다.
원활한 테스트를 위해여 구글 스프레드의 환경을 변경하였습니다. (슬랙에 게시예정)

feat(server): change the way data is extracted

---

packages/client/src/dashboard/presentation/components/Modal/Dataset.tsx
packages/client/src/dashboard/presentation/components/Modal/InputDatasets.tsx
packages/client/src/dashboard/presentation/components/Modal/InputLabels.tsx
packages/client/src/dashboard/presentation/components/Modal/LabelFilter.tsx
packages/client/src/dashboard/presentation/components/Modal/Modal.tsx
packages/client/src/dashboard/presentation/components/Modal/QueryFilterAttribute.tsx
packages/client/src/dashboard/presentation/components/Modal/SelectedFilter.tsx
packages/client/src/dashboard/presentation/components/Modal/Stepper.tsx
packages/client/src/dashboard/presentation/components/Modal/StickerStepper.tsx

✨ 그 외의 경우 :
- 적용된 변경 사항 요약
- 약간 광범위 한 부분에 리팩토링이 있어서, 빠른 머지가 필요할듯 싶어서 리팩토링 부분만 우선 올립니다.
- 추후에 실제 #299 부분의 기능 구현이 있을 예정입니다.

[좀급함] labelFilter 입력부분과 dataset 입력부분의 공통적인 부분을 추렸습니다.

---

packages/client/src/dashboard/infrastructure/http/graphql/createQuery.ts
packages/client/src/dashboard/presentation/components/Charts/LineChart.tsx
packages/client/src/dashboard/presentation/components/Modal/InputLabels.tsx
packages/client/src/dashboard/presentation/components/Modal/Modal.tsx
packages/client/src/dashboard/presentation/components/Modal/makeStickerData.ts
packages/client/src/dashboard/presentation/components/Sticker/Sticker.tsx

🐛 버그 픽스인 경우 :
- 버그를 재현하는 방법?
- 라벨에 숫자로 시작하거나 한글을 입력하면 발생
- 버그의 발생 원인?
- 라벨을 기반으로 쿼리를 작성하기 때문에 쿼리에서는 숫자로 시작하거나 한글을 입력 받을 경우 에러
- 어떻게 해결했는가?
- 다른방식으로 alias를 정해 주었다.

필터에 라벨 입력시 한글을 지원하지 않는 문제

---

packages/client/src/dashboard/presentation/components/Text/Text.tsx

Sticker의 Contents 중 하나인 Text component 생성
#287
🐛 버그 픽스인 경우 :
- 버그를 재현하는 방법?
- 버그의 발생 원인?
- 어떻게 해결했는가?
✨ 그 외의 경우 :
- 적용된 변경 사항 요약
- View mode
- Edit mode

feat(component): feat: add Text component

---

packages/client/src/dashboard/presentation/components/Charts/ChartData.ts
packages/client/src/dashboard/presentation/components/Common/EditToolBar.tsx
packages/client/src/dashboard/presentation/components/Modal/Dataset.tsx
packages/client/src/dashboard/presentation/components/Modal/InputDatasets.tsx
packages/client/src/dashboard/presentation/components/Modal/Modal.tsx
packages/client/src/dashboard/presentation/components/Modal/StickerStepper.tsx
packages/client/src/dashboard/presentation/components/Modal/TypeBox.tsx
packages/client/src/dashboard/presentation/components/Modal/makeStickerData.ts
packages/client/src/dashboard/presentation/components/Sticker/StickerContent.type.ts
yarn.lock

* 여러 스티커 타입의 입력을 받을 수 있는 모달을 만들기 위해 스텝을 고쳤다.
✨ 그 외의 경우 :
- 적용된 변경 사항 요약
- 먼저 type 상태를 이용해서 타입에 따라 스텝이 달라지게 만들었다.

feat(client/modal): make difftent flow depend on sticker type

---

packages/common/src/EntityColumn.ts
packages/server/src/api/api.service.ts
packages/server/src/main.ts
packages/server/src/schema.gql
packages/server/src/spread/spread.service.ts
packages/server/src/updater/name_types/updater.name.ts
packages/server/src/updater/updater.service.ts
packages/server/src/user_information/entity/user_access_card_information.entity.ts
packages/server/src/user_information/entity/user_information.entity.ts
packages/server/src/user_information/entity/user_other_information.entity.ts
packages/server/src/user_information/entity/user_personal_information.entity.ts
packages/server/src/user_job/entity/user_job.entity.ts
packages/server/src/user_payment/entity/user_computation_fund.entity.ts
packages/server/src/user_payment/entity/user_education_fund_state.entity.ts
packages/server/src/user_payment/entity/user_payment.entity.ts
packages/server/src/user_status/entity/user_status.entity.ts

validate_date를 추가하여 데이터의 유효성 시작 일자를 확인 할 수 있게 하였고, expired_date를 추가하여 데이터의 만료됨을 나타내도록 하였다.
기간 필터를 적용시킬때 데이터의 유효성을 체크할 수 있는 기준점이 필요했습니다.
✨ 그 외의 경우 :
- 적용된 변경 사항 요약
https://github.com/innovationacademy-kr/42dashboard/discussions/334#discussion-4264538
main.ts의 cors 수정이 필요합니다.

feat(server/updater): 데이터 유효성을 확인하여 기간 필터를 적용시킬 수 있는 데이터 추가

---

packages/client/src/dashboard/presentation/components/Modal/Modal.tsx
packages/client/src/dashboard/presentation/components/Modal/StickerStepper.tsx
packages/client/src/dashboard/presentation/components/Modal/TypeBox.tsx
packages/client/src/dashboard/presentation/components/Modal/stepper/StepButtons.tsx
packages/client/src/dashboard/presentation/components/Modal/stepper/StepHeader.tsx
packages/client/src/dashboard/presentation/pages/DashBoardPage.tsx

✨ 그 외의 경우 :
- 로직 변경은 없고, text와 table type 선택시 바로 다음 스텝에서 종료되도록 했습니다.

작업에 앞서 간단한 리팩을 했습니다.

---

packages/common/src/EntityColumn.ts
packages/server/src/user_information/argstype/joinedTable.ts

🐛 버그 픽스인 경우 :
- 버그를 재현하는 방법?
- 버그의 발생 원인?
- 어떻게 해결했는가?
✨ 그 외의 경우 :
- 적용된 변경 사항 요약

fix(server/common): joinedTable 빠진거 수정, EntityColumn 빠진거 수정

---

packages/server/src/schema.gql
packages/server/src/spread/spread.service.ts
packages/server/src/updater/updater.service.ts

getDataToModifyFromDB의 리턴값을 uri로 수정
수정시트에 대한 예외처리를 추가하고
sheet자동 연결을 위해 반환값을 수정하였습니다

feat/335: return uri to connect with sheet

---

packages/server/.gitignore
packages/server/src/auth/auth.controller.ts
packages/server/src/auth/entity/bocal.entity.ts
packages/server/src/main.ts
packages/server/src/spread/spread.service.ts
packages/server/src/user_information/user_information.controller.ts
packages/server/src/user_information/user_information.module.ts
packages/server/src/user_information/user_information.service.spec.ts
packages/server/src/user_information/user_information.service.ts

🐛 버그 픽스인 경우 :
- 버그를 재현하는 방법?
- 버그의 발생 원인?
- 어떻게 해결했는가?
✨ 그 외의 경우 :
- 적용된 변경 사항 요약

feat(server): 프리셋 저장, 수정, 삭제를 위한 API 추가

---

packages/client/src/dashboard/infrastructure/http/axios/axios.custom.ts
packages/client/src/dashboard/presentation/components/ModeDial/ModeDial.tsx

add data refresh button
#344
mode dial 내 refresh button 추가
클릭 시, data update api 호출

feat(board): feat: add data refresh button

---

packages/server/src/auth/entity/bocal.entity.ts
packages/server/src/user_information/user_information.controller.ts

info에 대한 정보 누락되는거 수정, 데이터 형식 수정
🐛 버그 픽스인 경우 :
- 버그를 재현하는 방법?
- 버그의 발생 원인?
- 어떻게 해결했는가?
✨ 그 외의 경우 :
- 적용된 변경 사항 요약

feat(server): 프리셋 API 보완수정

---

packages/server/src/auth/entity/bocal.entity.ts
packages/server/src/user_information/entity/user_access_card_information.entity.ts
packages/server/src/user_information/entity/user_information.entity.ts
packages/server/src/user_status/entity/user_status.entity.ts

🐛 버그 픽스인 경우 :
- 버그를 재현하는 방법?
- 버그의 발생 원인?
- 어떻게 해결했는가?
✨ 그 외의 경우 :
- 적용된 변경 사항 요약

fix(server): entity에 데이터타입 안맞는거수정

---

packages/client/src/dashboard/presentation/components/Modal/Dataset.tsx
packages/client/src/dashboard/presentation/components/Modal/Modal.tsx

🐛 버그 픽스인 경우 :
- 어떻게 해결했는가?
- prop이 배열이여서 인덱스로 접근해서 값을 바꾸면 랜더가 일어나지 않아서
- 스테이트를 하나 추가 했습니다.

fix(client): can edit dataset name

---

packages/client/src/dashboard/infrastructure/http/axios/axios.custom.ts
packages/client/src/dashboard/infrastructure/http/graphql/createModificationDataQuery.ts
packages/client/src/dashboard/infrastructure/http/graphql/createSaveModifiedDataQuery.ts
packages/client/src/dashboard/presentation/components/Dialog/EntityListItem.tsx
packages/client/src/dashboard/presentation/components/Dialog/ModificationDialog.tsx
packages/client/src/dashboard/presentation/components/Dialog/SaveButton.tsx
packages/client/src/dashboard/presentation/components/Modal/makeStickerData.ts
packages/client/src/dashboard/presentation/pages/DashBoardPage.tsx

✨ 그 외의 경우 :
- 적용된 변경 사항 요약
- 백엔드에서 제공된 쿼리로 디비를 수정할 수 있는 디자인을 완성했습니다.
1. 수정하기 버튼을 누르면2. 
2. 해당 스프레드 시트의 윈도우가 오픈이되고
3. 수정 후에 돌아와서 저장 버튼을 누르면 저장이 됩니다. 4. 
* query요청을 보낼시에 해당 db의 uri를 data로 넘겨주는 작업을 해주기로 약속 받았습니다.
* 해당 부분 완료되면 테스트 후 머지할 예정입니다.

DB를 수정할 수 있는 컴포넌트를 1차적으로 만들었습니다.

---

packages/client/src/dashboard/presentation/pages/DashBoardPage.tsx

🐛 버그 픽스인 경우 :
- 버그를 재현하는 방법?
- 버그의 발생 원인?
- 깃 작업하다가 지운부분이 적용이 안 된것 같습니다.
- 어떻게 해결했는가?
- 지웠습니다.

fix(client): duplicated modedial

---

packages/client/src/App.tsx
packages/client/src/dashboard/domain/user/user.repository.interface.ts
packages/client/src/dashboard/domain/user/user.service.ts
packages/client/src/dashboard/infrastructure/user.repository.ts
packages/client/src/dashboard/presentation/pages/Login.tsx

로그인이 되어 있는 경우, 로그인 페이지에 접근 시 대시보드 페이지로 라우팅 하기 위한 useEffect 적용
#343
- Login 컴포넌트 내 useEffect 적용
- Login.tsx을 pages 디렉토리로 이동

fix(login): fix: apply useEffect for navigate

---

packages/server/src/auth/auth.controller.ts

logout API 메서드를 Get에서 Post로 변경
fix #379
🐛 버그 픽스인 경우 :
- 버그를 재현하는 방법?
- 버그의 발생 원인?
- 어떻게 해결했는가?
✨ 그 외의 경우 :
- 적용된 변경 사항 요약

chore(server): logout API 메서드를 Get에서 Post로 변경

---

packages/client/src/dashboard/application/utils/DEFAULT_BACHELOR_PROPS.ts
packages/client/src/dashboard/application/utils/stringToNum.ts
packages/client/src/dashboard/infrastructure/http/graphql/createQuery.ts
packages/client/src/dashboard/presentation/components/Bachelor/Bachelor.tsx
packages/client/src/dashboard/presentation/components/Charts/LineChart.tsx
packages/client/src/dashboard/presentation/components/Dialog/ModificationDialog.tsx
packages/client/src/dashboard/presentation/components/Modal/Modal.tsx
packages/client/src/dashboard/presentation/components/Modal/StickerStepper.tsx
packages/client/src/dashboard/presentation/components/Modal/TypeBox.tsx
packages/client/src/dashboard/presentation/components/Modal/makeStickerData.ts
packages/client/src/dashboard/presentation/components/Sticker/StickerContent.type.ts
packages/client/src/dashboard/presentation/components/Sticker/StickerContentFactory.tsx
packages/client/src/dashboard/presentation/pages/DashBoardPage.tsx
packages/client/src/index.tsx

✨ 그 외의 경우 :
- 학적정보 테이블
- dataset 이름 적용

학적정보 테이블을 추가 했습니다. dataset label을 삭제할 수 있습니다.

---

packages/common/src/EntityColumn.ts
packages/common/src/tableName.ts
packages/server/src/common/EntityColumn.ts
packages/server/src/common/tableName.ts
packages/server/src/schema.gql
packages/server/src/spread/spread.service.ts
packages/server/src/updater/name_types/updater.name.ts
packages/server/src/updater/updater.module.ts
packages/server/src/updater/updater.service.ts
packages/server/src/user_information/argstype/joinedTable.ts
packages/server/src/user_information/entity/user_information.entity.ts
packages/server/src/user_information/utils/entityArray.utils.ts
packages/server/src/user_information/utils/getDomain.utils.ts
packages/server/src/user_payment/entity/user_payment.entity.ts
packages/server/src/user_payment/user_payment.module.ts
packages/server/src/user_payment/user_payment.resolver.ts
packages/server/src/user_payment/user_payment.service.ts

- 받아온 데이터의 유효성을 검사하는 작업을 하였습니다.
- 데이터 수정 시, 작업자가 데이터의 항목을 편하게 알아볼 수 있도록 시트와 컬럼이름을 메인과 맞춰주고자 하였습니다.
- 데이터 유효성 검사
- 컬럼 및 시트 이름 변환 함수 추가
- validate_date를 제외한 모든 날짜 컬럼은 동일한 날짜도 입력 가능하도록 변경
- 사라질 컬럼인 userEducationFundStatus를 주석처리하여 삭제 전 에러체크하였습니다.

feat(server): check data for validation and making function for translate spread 

---

packages/client/src/dashboard/application/services/useUser.tsx
packages/client/src/dashboard/domain/user/user.repository.interface.ts
packages/client/src/dashboard/domain/user/user.service.ts
packages/client/src/dashboard/infrastructure/http/axios/axios.custom.ts
packages/client/src/dashboard/presentation/pages/DashBoardPage.tsx

로그아웃 기능 구현
#297
- 로그아웃 구현
- 로그아웃 구현

feat(Logout): feat: add logout

---

packages/client/src/dashboard/application/utils/DEFAULT_TABLE_PROPS.ts
packages/client/src/dashboard/presentation/components/Dialog/EntityListItem.tsx
packages/client/src/dashboard/presentation/components/Dialog/ModificationDialog.tsx
packages/client/src/dashboard/presentation/components/Dialog/RequestButton.tsx
packages/client/src/dashboard/presentation/components/Dialog/SaveButton.tsx

🐛 버그 픽스인 경우 :
- 버그를 재현하는 방법?
- 버그의 발생 원인?
- 어떻게 해결했는가?
✨ 그 외의 경우 :
- 적용된 변경 사항 요약

refactor(client): refac update db

---

packages/client/src/dashboard/presentation/pages/Login.tsx

로그인 페이지 스타일링
- 로그인 페이지 스타일링
- 
- 로그인 페이지 스타일링

style(Login): style: login page styling

---

packages/client/src/dashboard/presentation/components/Modal/QueryFilterAttribute.tsx

✨ 그 외의 경우 :
- 필드를 채워놓지 않았을 경우 뜨는 에러메시지 변경

fix(client): fix alert msg

---

packages/client/src/dashboard/presentation/components/Modal/Modal.tsx
packages/client/src/dashboard/presentation/components/Modal/StickerStepper.tsx
packages/client/src/dashboard/presentation/components/Modal/filterAttributes/menuItems/returnEntities.tsx

fix(client): modal entity name to hangeul

---

packages/client/src/dashboard/application/services/useBoard.tsx
packages/client/src/dashboard/application/services/useSectionDatas.tsx

🐛 버그 픽스인 경우 :
- 처음 섹션 생성할때 위치 조정

style(client): amend initial position when create section in board

---

packages/client/src/dashboard/presentation/components/Modal/QueryFilterAttribute.tsx

fix(client/modal): filter 설정하는 save 버튼 수정

---

packages/client/src/dashboard/presentation/components/Modal/Modal.tsx

모달 위치 변경
#403
- 모달의 위치가 일정하지 않음
🐛 버그 픽스인 경우 :
- 버그를 재현하는 방법?
- 그리드 레이아웃의 요소가 여러 개 있는 상태에서 모달 호출
- 버그의 발생 원인?
- 모달을 호출하는 요소 기준으로 위치를 정해서 모달 위치가 계속 변경됨
- 어떻게 해결했는가?
- 모달 position 속성을 fixed로 변경
✨ 그 외의 경우 :
- 적용된 변경 사항 요약

fix(modal): fix:modal position

---

packages/server/src/auth/auth.controller.ts
packages/server/src/auth/auth.service.ts
packages/server/src/auth/entity/bocal.entity.ts
packages/server/src/user_information/argstype/filter.argstype.ts
packages/server/src/user_information/user_information.service.spec.ts
packages/server/src/user_information/user_information.service.ts
packages/server/src/user_information/utils/entityArray.utils.ts
packages/server/src/user_information/utils/operatorDict.utils.ts

기간 필터링 로직을 수정 및 보완하였습니다.
시간에 쫓겨 만들다보니 가독성이 매우 안좋습니다.
나중에 리팩터링 하면서 가독성 좋게 수정하겠습니다
✨ 그 외의 경우 :
- 적용된 변경 사항 요약

기간 필터링 로직 보완 수정

---

packages/client/src/dashboard/infrastructure/http/graphql/createQuery.ts
packages/client/src/dashboard/presentation/components/Dialog/RequestButton.tsx
packages/client/src/dashboard/presentation/components/Dialog/SaveButton.tsx
packages/client/src/dashboard/presentation/components/Modal/Dataset.tsx
packages/client/src/dashboard/presentation/components/Modal/QueryFilterAttribute.tsx
packages/client/src/dashboard/presentation/components/Modal/StickerStepper.tsx
packages/client/src/dashboard/presentation/components/Modal/filterAttributes/FilterAttribute.tsx
packages/client/src/dashboard/presentation/components/Modal/filterAttributes/ValueAttribute.tsx
packages/client/src/dashboard/presentation/components/Modal/filterAttributes/menuItems/returnColumns.tsx
packages/client/src/dashboard/presentation/components/Modal/filterAttributes/menuItems/returnValues.tsx
packages/client/src/dashboard/presentation/components/SideBar/PresetListItem.tsx
packages/client/src/dashboard/presentation/components/Sticker/Filter.type.ts

🐛 버그 픽스인 경우 :
- 각종 console.log 삭제
- select 항목중에 none 제거
- entityName type 수정
- 사소한 리팩

fix(client): error if entityName & column is empty

---

packages/client/src/dashboard/presentation/components/Modal/filterAttributes/ValueAttribute.tsx
packages/client/src/dashboard/presentation/components/Modal/filterAttributes/menuItems/returnValues.tsx

🐛 버그 픽스인 경우 :
- 버그를 재현하는 방법?
- string이 아닌 타입의 밸류로 쿼리요청
- 어떻게 해결했는가?
- givenvalue값을 받을때 string으로 형변환
✨ 그 외의 경우 :
- 적용된 변경 사항 요약

gql 쿼리가 넘버타입이로 넘어가는 밸류에 대해서 스트링으로 형변환을 해주었습니다.

---

packages/server/src/common/EntityColumn.ts
packages/server/src/schema.gql
packages/server/src/spread/spread.service.ts
packages/server/src/updater/updater.service.ts
packages/server/src/user_information/argstype/updateSheet.argstype.ts

modify page에서 데이터를 삭제하고 삭제된 값을 제외하거나 포함해서 볼 수 있도록 기능을 만들었습니다.
feat 415
수정시트에서 유저테이블을 제외한 모든 테이블의 목록을 삭제할 수 있도록하였습니다.
수정시트에서 항목을 삭제하고, 복구할 수 있도록 만들었습니다.

feat(server/delete modify page): feat: delete function for modify page

---

packages/client/src/dashboard/presentation/components/Modal/InputLabels.tsx
packages/client/src/dashboard/presentation/components/Modal/LabelFilter.tsx
packages/client/src/dashboard/presentation/components/Modal/QueryFilterAttribute.tsx
packages/client/src/dashboard/presentation/components/Modal/SelectedFilter.tsx
packages/client/src/dashboard/presentation/components/Modal/StickerStepper.tsx

🐛 버그 픽스인 경우 :
- 저장 버튼을 누를때 value들을 리셋해주었습니다.
✨ 그 외의 경우 :
- 적용된 변경 사항 요약

fix(client): reset after add label filter

---

packages/server/src/auth/auth.controller.ts
packages/server/src/auth/auth.service.ts
packages/server/src/auth/entity/bocal.entity.ts
packages/server/src/schema.gql
packages/server/src/user_information/user_information.service.ts
packages/server/src/user_information/utils/entityArray.utils.ts

🐛 버그 픽스인 경우 :
- 버그를 재현하는 방법?
- 버그의 발생 원인?
- 어떻게 해결했는가?
✨ 그 외의 경우 :
- 적용된 변경 사항 요약

fix(server): validate_date 속성 값 못읽는 에러 수정

---

.gitignore
packages/client/.env.example
packages/client/package.json
packages/client/src/dashboard/infrastructure/http/axios/axios.instance.ts
packages/client/src/dashboard/infrastructure/preset.repository.ts
packages/client/src/dashboard/infrastructure/presetList.repository.ts
packages/client/src/dashboard/presentation/components/Dialog/RequestButton.tsx
packages/client/src/dashboard/presentation/pages/Login.tsx
packages/client/src/index.tsx
packages/server/.env.example
packages/server/package.json
packages/server/src/app.module.ts
packages/server/src/auth/auth.controller.ts
yarn.lock

개발환경과 배포환경을 분리하기 위한 작업 입니다.
> `client` - 환경에 맞는 환경변수 파일을 추가해주어야 합니다.  
> `server` - 환경에 맞는 환경변수 파일을 추가하고, `config` 디렉토리 내의 설정파일들을 변경해주어야 합니다.

build(root): development 환경 과 production 환경 구분을 위한 환경변수 추가 작업

---

packages/client/src/dashboard/application/services/useBoard.tsx

🐛 버그 픽스인 경우 :
- section의 리사이즈가 일어나면 윈도우의 리사이즈를 일으켰습니다.
✨ 그 외의 경우 :
- 적용된 변경 사항 요약

fix(client): manually trigger  window resize event

---

packages/client/src/dashboard/infrastructure/http/graphql/createModificationDataQuery.ts
packages/client/src/dashboard/infrastructure/http/graphql/createSaveModifiedDataQuery.ts
packages/client/src/dashboard/presentation/components/Dialog/EntityListItem.tsx
packages/client/src/dashboard/presentation/components/Dialog/RequestButton.tsx
packages/client/src/dashboard/presentation/components/Dialog/SaveButton.tsx
packages/client/src/dashboard/presentation/components/Dialog/WithButton.tsx
packages/client/src/dashboard/presentation/components/Modal/InputLabels.tsx
packages/client/src/dashboard/presentation/components/Modal/LabelFilter.tsx
packages/client/src/dashboard/presentation/components/Modal/Modal.tsx

✨
- update db 요청을 withDeleted 옵션으로 보낼 수 있습니다.

feat(client): update db withdeleted option

---

packages/server/src/auth/auth.service.ts
packages/server/src/user_information/user_information.service.ts
packages/server/src/user_information/utils/entityArray.utils.ts

필터 옵션에서 latest을 true로 줄때 문제가 발생함을 확인하고 이를 수정하였습니다.
🐛 버그 픽스인 경우 :
- 버그를 재현하는 방법?
- 버그의 발생 원인?
- 어떻게 해결했는가?
✨ 그 외의 경우 :
- 적용된 변경 사항 요약

fix(server): 기간 필터링에서 값을 제대로 뽑아내지 못하는 문제를 해결

---

packages/server/src/auth/auth.service.ts
packages/server/src/user_information/user_information.controller.ts
packages/server/src/user_information/user_information.service.ts

🐛 버그 픽스인 경우 :
- 버그를 재현하는 방법?
- 버그의 발생 원인?
- 어떻게 해결했는가?
✨ 그 외의 경우 :
- 적용된 변경 사항 요약

fix(server): user테이블에 한해서 기간필터링이 적용되지 않는 문제 해결

---

packages/client/src/dashboard/presentation/components/Modal/filterAttributes/menuItems/returnValues.tsx

🐛 버그 픽스인 경우 :
- 버그를 재현하는 방법?
- value값이 없는 엔티티와 컬럼으로 쿼리 요청을 보낼경우
- null을 tostring 할 수 없어서 에러발생
✨ 그 외의 경우 :
- 적용된 변경 사항 요약

fix(client'): error if return given value is null

---

packages/client/src/dashboard/application/utils/DEFAULT_BACHELOR_PROPS.ts
packages/client/src/dashboard/presentation/components/Modal/Dataset.tsx
packages/client/src/dashboard/presentation/components/Modal/InputLabels.tsx
packages/client/src/dashboard/presentation/components/Modal/Modal.tsx
packages/client/src/dashboard/presentation/components/Modal/SelectedFilter.tsx
packages/client/src/dashboard/presentation/components/Modal/StickerStepper.tsx
packages/client/src/dashboard/presentation/components/Modal/filterAttributes/ValueAttribute.tsx
packages/common/src/Operator.ts
packages/server/src/auth/auth.controller.ts
packages/server/src/auth/auth.service.ts

✨ 그 외의 경우 :
- 차트 라벨 선택 스텝에서 이미 선택된 필터를 삭제 할 수 있습니다.

feat(client): remove selected filter

---

packages/server/src/user_information/user_information.controller.ts
packages/server/src/user_information/user_information.service.ts
packages/server/src/user_information/utils/entityArray.utils.ts

🐛 버그 픽스인 경우 :
- 버그를 재현하는 방법?
- 버그의 발생 원인?
- 어떻게 해결했는가?
✨ 그 외의 경우 :
- 적용된 변경 사항 요약

fix(server): 기간 필터링 로직 수정

---

packages/client/src/dashboard/presentation/components/Modal/Dataset.tsx
packages/client/src/dashboard/presentation/components/Modal/InputLabels.tsx
packages/client/src/dashboard/presentation/components/Modal/LabelFilter.tsx
packages/client/src/dashboard/presentation/components/Modal/Modal.tsx
packages/client/src/dashboard/presentation/components/Modal/QueryFilterAttribute.tsx
packages/client/src/dashboard/presentation/components/Modal/SelectedFilter.tsx

✨ 그 외의 경우 :
- 적용된 변경 사항 요약
- 선택된 필터를 삭제할 수 있고 라벨이름을 수정할 수 있습니다.
- 데이터셋을 삭제 할 수 있습니다.

필터 수정 및 삭제 및 라벨 수정

---

packages/server/src/updater/updater.service.ts

에러 값들을 배열로 보내 작업하기 쉽게 만들었습니다. pk가 늘어나는 부분은 향후 수정예정입니다.

feat(server/spread): feat: making error checker to use better

---

packages/client/src/dashboard/infrastructure/http/axios/axios.custom.ts
packages/client/src/dashboard/infrastructure/http/axios/axios.instance.ts
packages/client/src/dashboard/presentation/components/Footer/Footer.tsx
packages/client/src/dashboard/presentation/pages/DashBoardPage.tsx

CRUD error check를 위한 custom axios 추가 및 적용
#408
- CRUD error check를 위한 custom axios 추가 및 적용
- test sample 추가 후, error에 대한 출력 추가 예정

feat(CRUD): feat: add CRUD error check api

---

packages/server/src/user_information/user_information.service.ts
packages/server/src/user_information/utils/entityArray.utils.ts

🐛 버그 픽스인 경우 :
- 버그를 재현하는 방법?
- 버그의 발생 원인?
- 어떻게 해결했는가?
✨ 그 외의 경우 :
- 적용된 변경 사항 요약

fix(server): table 불러올때 에러발생해서 코드 수정

---

packages/client/src/dashboard/application/services/useBoard.tsx
packages/client/src/dashboard/application/services/usePreset.tsx
packages/client/src/dashboard/domain/preset/preset.repository.interface.ts
packages/client/src/dashboard/domain/preset/preset.service.ts
packages/client/src/dashboard/domain/preset/preset.type.ts
packages/client/src/dashboard/infrastructure/preset.repository.ts
packages/client/src/dashboard/infrastructure/presetList.repository.ts
packages/client/src/dashboard/infrastructure/store/preset.store.ts
packages/client/src/dashboard/presentation/components/Board/Board.tsx
packages/client/src/dashboard/presentation/components/Common/EditToolBar.tsx
packages/client/src/dashboard/presentation/components/Footer/Footer.tsx
packages/client/src/dashboard/presentation/components/SideBar/PresetListItem.tsx
packages/client/src/dashboard/presentation/components/SideBar/SideBar.tsx

🐛 버그 픽스인 경우 :
preset에 이름 변경을 할 수 있습니다.

preset 이름이 변경이 됩니다.

---

packages/client/src/dashboard/presentation/components/Board/Section.tsx
packages/client/src/dashboard/presentation/components/Common/EditToolBar.tsx

섹션에 적용되는 기간/기수 필터 값 출력
- 섹션에 적용되는 기간/기수 필터 값 출력

feat(filter): feat: show section filter value

---

packages/client/src/dashboard/application/services/useBoard.tsx
packages/client/src/dashboard/presentation/components/Charts/BarChart.tsx
packages/client/src/dashboard/presentation/components/Charts/ChartData.ts
packages/client/src/dashboard/presentation/components/Charts/LineChart.tsx
packages/client/src/dashboard/presentation/components/Charts/PieChart.tsx

- 차트 스타일링
- 적용된 변경 사항 요약
- piechart에서 data hover시 dataset 정보 나타내줌, data hover시 퍼센트 보여짐
feat #461

feat(client/chart): chartjs option을 수정하여 차트를 보기 좋게 만들었습니다

---

packages/client/src/dashboard/presentation/components/PeriodModal/PeriodModal.tsx

필터 초기화 구현
- 필터 초기화 필요
- 필터 초기화 구현

feat(filter): feat: add filter init

---

packages/server/src/user_information/user_information.controller.ts
packages/server/src/user_information/user_information.service.ts
packages/server/src/user_information/utils/entityArray.utils.ts

filtering 적용하는 부분의 코드 주석추가, 리팩터링  진행중

filtering 적용하는 부분의 코드 주석추가, 리팩터링  진행중

---

packages/client/src/dashboard/application/services/useBoard.tsx
packages/client/src/dashboard/application/services/usePreset.tsx
packages/client/src/dashboard/infrastructure/preset.repository.ts
packages/client/src/dashboard/infrastructure/store/preset.store.ts
packages/client/src/dashboard/presentation/components/Footer/Footer.tsx
packages/client/src/dashboard/presentation/components/SideBar/PresetListItem.tsx
packages/client/src/dashboard/presentation/components/SideBar/SideBar.tsx
packages/client/src/dashboard/presentation/pages/DashBoardPage.tsx

🐛 버그 픽스인 경우 :
- 리프레시 하고 프리셋 목록 섞이는 거랑
- 이름 제대로 안바뀌는 거
- 새로운 프리셋 추가했을때 제대로 저장 안되는거 수정
✨ 그 외의 경우 :
- 적용된 변경 사항 요약

fix(client): rename preset, refresh not occur random list

---

packages/common/src/EntityColumn.ts
packages/server/src/common/EntityColumn.ts
packages/server/src/updater/name_types/updater.name.ts
packages/server/src/updater/updater.service.ts
packages/server/src/user_payment/entity/user_payment.entity.ts

table 변경에 의해 FE에서 제공해야하는 목록도 수정이 필요하여 작업하였습니다.

refactor(server/updater): table 변경에 의한 entity column 수정 및 주석 제거

---

packages/client/src/dashboard/presentation/pages/Login.tsx

로그인 버튼 크기 및 배경색 변경
- 로고 글씨와 배경이 모두 검정색이라 글씨가 보이지 않음
- 로그인 페이지 배경색 변경
- 로그인 버튼 크기 변경

chore(login): chore: edit login button

---

packages/client/src/dashboard/presentation/pages/DashBoardPage.tsx

user intra name의 첫 글자가 profile에 표시
- user intra name의 첫 글자가 profile에 표시

feat(profile): feat: 각 user의 intra name에 따른 profile 아이콘 보이도록 변경

---

packages/client/src/dashboard/presentation/components/Charts/BarChart.tsx
packages/client/src/dashboard/presentation/components/Charts/LineChart.tsx
packages/client/src/dashboard/presentation/components/Charts/PieChart.tsx
packages/client/src/dashboard/presentation/components/Dialog/WithButton.tsx

- 시각적으로 어떤 체크박스인지 설명이 필요했습니다.
- 적용된 변경 사항 요약
- 체크박스 옆에 '삭제된 데이터 포함'이라는 label을 추가해주었습니다.

수정하기 페이지에서 삭제된 데이터 추가하는 체크박스에 label 추가

---

packages/client/src/dashboard/presentation/components/Charts/BarChart.tsx
packages/client/src/dashboard/presentation/components/Charts/LineChart.tsx
packages/client/src/dashboard/presentation/components/Charts/PieChart.tsx

- dataset이 없을 경우 label에 undefined가 출력됩니다.
- 적용된 변경 사항 요약

feat(client/chart): dataset이 없을 때 label 수정

---

.vscode/launch.json
packages/server/src/schema.gql
packages/server/src/spread/msg/errorMsg.msg.ts
packages/server/src/spread/spread.resolver.ts
packages/server/src/spread/spread.service.ts
packages/server/src/updater/updater.service.ts

transfer유저가 들어왔을 경우 api를 받아올 수 없는 현상이있었습니다.
위의 경우 api처리를 하지 않는 방식으로 방어해주었습니다.
전출이긴해도 앞으로 기록을 사용할 수 있기에, 삭제처리하지 않는 방향으로 진행하였습니다.
+++
메인 및 수정시트의 예외처리 값을 추가해줬습니다. 점차적으로 수정 작업을 더할 것 입니다.

Feat(server) 메인 및 수정시트의 예외처리 값을 추가해줬습니다. 

---

packages/client/src/App.tsx
packages/client/src/dashboard/presentation/components/AppBar/AppBar.tsx
packages/client/src/dashboard/presentation/components/AppBar/Profile/Profile.tsx
packages/client/src/dashboard/presentation/components/Board/Board.tsx
packages/client/src/dashboard/presentation/components/Board/Section.tsx
packages/client/src/dashboard/presentation/components/Board/styles.css
packages/client/src/dashboard/presentation/components/Common/EditToolBar.tsx
packages/client/src/dashboard/presentation/components/Footer/Footer.tsx
packages/client/src/dashboard/presentation/pages/DashBoardPage.tsx

chore(theme): chore: edit theme

---

packages/client/src/dashboard/application/services/useBoard.tsx
packages/client/src/dashboard/application/services/useMode.tsx
packages/client/src/dashboard/application/services/usePreset.tsx
packages/client/src/dashboard/presentation/components/Board/Board.tsx
packages/client/src/dashboard/presentation/components/Board/Section.tsx
packages/client/src/dashboard/presentation/components/Footer/Footer.tsx
packages/client/src/dashboard/presentation/components/SideBar/PresetListItem.tsx
packages/client/src/dashboard/presentation/components/Sticker/Sticker.tsx
packages/client/src/dashboard/presentation/components/Sticker/StickerContentFactory.tsx
packages/client/src/dashboard/presentation/components/Table/Table.tsx

🐛 버그 픽스인 경우 :
- useMode를 Board, Section, Sticker, StickerContentFactory 모두에서 사용하며 발생되는 랜더링 이슈해결

perf(client): useMode 사용에서 발생하는 이슈 수정

---

packages/client/src/dashboard/infrastructure/http/axios/axios.instance.ts
packages/server/src/auth/dto/errObject.dto.ts
packages/server/src/spread/msg/errorMsg.msg.ts
packages/server/src/spread/spread.service.ts
packages/server/src/updater/name_types/updater.name.ts
packages/server/src/updater/updater.service.ts
packages/server/src/user_status/user_status.service.ts

각종 에러를 수정하였습니다.
수정 및 삭제에 대한 로직을 엄격하게 강화하였고, 
도메인 중복이나 기타 에러사항 수정하였습니다.

fix(server) : 각종 오류수정

---

packages/client/src/dashboard/presentation/components/Footer/Footer.tsx
packages/client/src/dashboard/presentation/pages/DashBoardPage.tsx

getError alert 요구사항에 맞춰 변경
- BE 요청
- getError alert 요구사항에 맞춰 변경

feat(getError): feat: getError 변경

---

packages/server/src/api/api.service.ts
packages/server/src/app.module.ts
packages/server/src/spread/spread.service.ts
packages/server/src/type.ts/entityType.ts
packages/server/src/updater/updater.service.ts

모아진 데이터를 기반으로 산출하던 과거 데이터를 디비에 로깅하면서 관리가 어려워 졌습니다. 그래서 따로 관리하지 않고 스프레드에 있는 데이터 기반으로 계산하여 디비에 저장하였습니다.
- 적용된 변경 사항 요약
루나님께서 요청하신 지원금 남은 개월 수 도 추가하였습니다.

fix(server/updater): computation 산정 계산 값 처리

---

packages/client/src/dashboard/presentation/components/Board/Board.tsx
packages/client/src/dashboard/presentation/components/Board/Section.tsx
packages/client/src/dashboard/presentation/components/Common/EditToolBar.tsx

기간/기수 필터를 표시하기 위해 섹션 툴바 수정
🐛 버그 픽스인 경우 :
- 버그를 재현하는 방법?
- 기간/기수 필터 적용
- 버그의 발생 원인?
- 투명도 0
- 어떻게 해결했는가?
- 스타일 변경
✨ 그 외의 경우 :
- View mode 에서 적용된 필터를 알 수 있도록 변경

fix(SectionToolBar): fixed: edit SectionEditToolBar

---

packages/client/src/dashboard/application/services/usePreset.tsx
packages/client/src/dashboard/domain/preset/preset.repository.interface.ts
packages/client/src/dashboard/domain/preset/preset.service.ts
packages/client/src/dashboard/domain/presetList/presetList.service.ts
packages/client/src/dashboard/infrastructure/http/graphql/createQuery.ts
packages/client/src/dashboard/infrastructure/http/graphql/createValueQuery.ts
packages/client/src/dashboard/infrastructure/preset.repository.ts
packages/client/src/dashboard/infrastructure/presetList.repository.ts
packages/client/src/dashboard/infrastructure/store/preset.store.ts
packages/client/src/dashboard/presentation/components/Footer/Footer.tsx
packages/client/src/dashboard/presentation/components/SideBar/PresetListItem.tsx
packages/client/src/dashboard/presentation/components/SideBar/SideBar.tsx
packages/server/src/spread/spread.service.ts

🐛 버그 픽스인 경우 :
- 뷰에서 에딧모드로 변경될때 수정된 프리셋 라벨을 저장하도록 했는데
- 라벨 수정하는 메소드 안에 프리셋을 업데이트 하는 로직이 있어서
- 셀렉티드가 업데이트 됐습니다. 해당 부분 주석처리 했습니다.
- 그 외 필요없거나 불필요한 async메소드 수정했습니다.

fix(client): edit selected randomly

---

packages/server/src/schema.gql
packages/server/src/type.ts/entityType.ts
packages/server/src/updater/name_types/updater.name.ts
packages/server/src/updater/updater.resolver.ts
packages/server/src/updater/updater.service.ts

Fix(server): 배포전, 마지막 수정입니다.

---

packages/client/src/dashboard/presentation/pages/DashBoardPage.tsx

logout api 401 error에 대한 처리 추가
- BE 요청
- logout api 401 에러가 오는 경우, 유저 정보, 토큰 삭제 및 로그인 페이지로 라우팅 처리

feat(logout): logout api error에 대한 처리

---

packages/client/src/dashboard/presentation/components/SideBar/SideBar.tsx

feat(sidebar): remove future list

---

packages/client/src/dashboard/presentation/pages/DashBoardPage.tsx

feat(profile): remove mypage

---

packages/client/src/App.tsx
packages/client/src/dashboard/application/services/useMode.tsx
packages/client/src/dashboard/presentation/components/Board/Board.tsx
packages/client/src/dashboard/presentation/components/Board/Section.tsx
packages/client/src/dashboard/presentation/components/Footer/Footer.tsx
packages/client/src/dashboard/presentation/pages/DashBoardPage.tsx

feat(client): implement fullview

---

packages/client/package.json
packages/client/src/dashboard/presentation/components/Common/EditToolBar.tsx
packages/client/src/dashboard/presentation/components/Sticker/Sticker.tsx
yarn.lock

feat(client/sticker): add export function in sticker
